# Generated by Django 5.2.13 on 2026-04-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalemaillog',
            name='bitrix_entity_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionalemaillog',
            name='bitrix_entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
