# Generated by Django 5.2.13 on 2026-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brevoaccount',
            name='contact_attribute_map',
            field=models.JSONField(blank=True, default=dict, help_text='Map internal fields to Brevo attribute names for this account. Leave empty to use defaults. Keys: first_name, last_name, company, position, source, bitrix_id. Example: {"first_name": "NOMBRE", "last_name": "APELLIDO"}'),
        ),
    ]
