# Generated by Django 5.2.13 on 2026-04-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('member_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret_encrypted', models.TextField()),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('application_token', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_endpoint', models.URLField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_portals', to='tenants.tenant')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
