# Generated by Django 5.2.13 on 2026-04-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitrix24', '0001_initial'),
        ('brevo', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('external_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('error', 'Error')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('bitrix_contact_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('brevo_contact_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('brevo_lists', models.JSONField(blank=True, default=list)),
                ('subscription_status', models.CharField(choices=[('unknown', 'Unknown'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('blacklisted', 'Blacklisted')], default='unknown', max_length=50)),
                ('bitrix_updated_at', models.DateTimeField(blank=True, null=True)),
                ('brevo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_direction', models.CharField(blank=True, choices=[('bitrix_to_brevo', 'Bitrix to Brevo'), ('brevo_to_bitrix', 'Brevo to Bitrix'), ('reconcile', 'Reconcile')], max_length=50, null=True)),
                ('sync_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('has_sync_error', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitrix24.bitrixportal')),
                ('brevo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevo.brevoaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('tenant', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bitrix', 'Bitrix24'), ('brevo', 'Brevo'), ('system', 'System')], max_length=50)),
                ('direction', models.CharField(blank=True, choices=[('bitrix_to_brevo', 'Bitrix to Brevo'), ('brevo_to_bitrix', 'Brevo to Bitrix'), ('transactional', 'Transactional'), ('install', 'Install'), ('webhook', 'Webhook')], max_length=50, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('ignored', 'Ignored'), ('error', 'Error'), ('warning', 'Warning')], max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync.syncedcontact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
